name: task_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.2.0
  firebase_core: ^3.4.0
  firebase_database: ^11.1.1
  flutter:
    sdk: flutter
  flutter_slidable:
     git:
      url: https://github.com/letsar/flutter_slidable.git
      ref: master
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data.json
    - assets/logo.jpg
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.jpg"
  web:
    generate: true
    image_path: "assets/logo.jpg"
  windows:
    generate: true
    image_path: "assets/logo.jpg"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/logo.jpg"
