// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBB2jYY_EZBlyOgvIp84Eso54ieXknVKE',
    appId: '1:7054745973:web:32ff9c1faaeabe8224733c',
    messagingSenderId: '7054745973',
    projectId: 'task-tracker-9c52d',
    authDomain: 'task-tracker-9c52d.firebaseapp.com',
    databaseURL: 'https://task-tracker-9c52d-default-rtdb.firebaseio.com',
    storageBucket: 'task-tracker-9c52d.appspot.com',
    measurementId: 'G-Z710SYPHEL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuLoR-a71a8aZuX18IELTZTtSU6X6SvH4',
    appId: '1:7054745973:android:710721b7cd0dd70624733c',
    messagingSenderId: '7054745973',
    projectId: 'task-tracker-9c52d',
    databaseURL: 'https://task-tracker-9c52d-default-rtdb.firebaseio.com',
    storageBucket: 'task-tracker-9c52d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT0mbUAJZKf8AXsbQE8fyMF6h3s-MzXzg',
    appId: '1:7054745973:ios:9185a3c7563ba02a24733c',
    messagingSenderId: '7054745973',
    projectId: 'task-tracker-9c52d',
    databaseURL: 'https://task-tracker-9c52d-default-rtdb.firebaseio.com',
    storageBucket: 'task-tracker-9c52d.appspot.com',
    iosBundleId: 'com.pravii.taskTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT0mbUAJZKf8AXsbQE8fyMF6h3s-MzXzg',
    appId: '1:7054745973:ios:62582fb55bc8153a24733c',
    messagingSenderId: '7054745973',
    projectId: 'task-tracker-9c52d',
    databaseURL: 'https://task-tracker-9c52d-default-rtdb.firebaseio.com',
    storageBucket: 'task-tracker-9c52d.appspot.com',
    iosBundleId: 'com.example.taskTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBB2jYY_EZBlyOgvIp84Eso54ieXknVKE',
    appId: '1:7054745973:web:e255a228be2fa6f824733c',
    messagingSenderId: '7054745973',
    projectId: 'task-tracker-9c52d',
    authDomain: 'task-tracker-9c52d.firebaseapp.com',
    databaseURL: 'https://task-tracker-9c52d-default-rtdb.firebaseio.com',
    storageBucket: 'task-tracker-9c52d.appspot.com',
    measurementId: 'G-0HV6FD6GZ8',
  );
}
